JoomGalleryfriends/JoomGallery

components/com_joomgallery/models/detail.php, language/en-GB/en-GB.com_joomgallery.iptc.ini
This is a redo of JoomGallery/JoomGallery#139.
=> Fix character set encoding and other problems with IPTC data

administrator/components/com_joomgallery/controllers/control.php
=> Fix PHP 7 notice during errorneous install, fixes #4

administrator/components/com_joomgallery/models/forms/category.xml, administrator/components/com_joomgallery/sql/install.mysql.utf8.sql, administrator/components/com_joomgallery/sql/updates/mysql/3.4.0.sql, administrator/components/com_joomgallery/tables/joomgallerycategories.php, administrator/components/com_joomgallery/views/category/tmpl/form.php, administrator/language/en-GB/en-GB.com_joomgallery.ini, components/com_joomgallery/controller.php, components/com_joomgallery/models/category.php, components/com_joomgallery/models/comments.php, components/com_joomgallery/models/detail.php, components/com_joomgallery/models/favourites.php, components/com_joomgallery/models/search.php, components/com_joomgallery/models/toplist.php, components/com_joomgallery/models/vote.php, components/com_joomgallery/views/category/view.html.php, components/com_joomgallery/views/detail/view.html.php, components/com_joomgallery/views/favourites/tmpl/default.php, components/com_joomgallery/views/favourites/tmpl/list.php, components/com_joomgallery/views/favourites/view.html.php, components/com_joomgallery/views/image/view.raw.php, components/com_joomgallery/views/search/tmpl/default.php, components/com_joomgallery/views/search/view.html.php, components/com_joomgallery/views/toplist/tmpl/default.php, components/com_joomgallery/views/toplist/view.html.php, language/en-GB/en-GB.com_joomgallery.ini
This is a redo of https://github.com/JoomGallery/JoomGallery/pull/165
Thanks to @Erftralle for help with this feature.
=> Extended Category Settings

administrator/components/com_joomgallery/helpers/upload.php
This is a possible fix for issue https://github.com/JoomGalleryfriends/JoomGallery/issues/14
Maybe someone knows a better solution?
=> Fix error in long time upload

administrator/components/com_joomgallery/views/control/tmpl/default_notapprovedcomments.php, administrator/components/com_joomgallery/views/control/tmpl/default_notapprovedimages.php, administrator/components/com_joomgallery/views/control/tmpl/default_popularimages.php, administrator/components/com_joomgallery/views/control/tmpl/default_topdownloads.php, media/joomgallery/css/admin.joomgallery.css, media/joomgallery/css/joomgallery.css
This is a redo of https://github.com/JoomGalleryfriends/JoomGallery/pull/17 with a few small changes to the proposal.
Thanks to @reilldesign for the contribution.
=> Improved thumbnail display

administrator/components/com_joomgallery/changelog.xml, administrator/components/com_joomgallery/joomgallery.xml, administrator/components/com_joomgallery/script.php, components/com_joomgallery/interface.php, joomgallery.xml, script.php
This pull request prepares the release of JoomGallery 3.4.0.
Please check whether an update of a former JoomGallery (e.g. JoomGallery 3.3.5) as well as a complete new installation works and give feedback. Thanks.
If successful I will merge the branch v3.4.0 to master, adjust the release date in the respective xml files and release the JoomGallery 3.4.0.
=> Preparations for the release of JoomGallery 3.4.0

administrator/components/com_joomgallery/views/config/tmpl/default.php
Two lines are douple in default.php
=> Remove duplicate lines

administrator/components/com_joomgallery/views/categories/tmpl/default.php, components/com_joomgallery/controllers/report.php, components/com_joomgallery/models/detail.php, components/com_joomgallery/views/usercategories/tmpl/default.php
This PR should fix php warnings when using php 7.4
=> Fix php 7.4 deprecated warnings

components/com_joomgallery/views/report/tmpl/default.php
The report window currently is overflowing horizontally on small screens.
This PR should fix this.
=> Set max-width for report window

components/com_joomgallery/controllers/map.php, components/com_joomgallery/views/detail/tmpl/default.php, components/com_joomgallery/views/detail/view.html.php, language/en-GB/en-GB.com_joomgallery.ini
This pull request is a proposal to fix issue #47 . See #47 for more information.
=> Makes the display of maps in the detail view GDPR compliant

components/com_joomgallery/models/detail.php
=> Fixes warning when EXIF tag GPSAltitudeRef is displayed in detail view

administrator/components/com_joomgallery/changelog.xml, administrator/components/com_joomgallery/joomgallery.xml, administrator/components/com_joomgallery/script.php, components/com_joomgallery/controllers/map.php, components/com_joomgallery/interface.php, joomgallery.xml, script.php
This pull request prepares the release of JoomGallery 3.5.0.
Please check whether an update of a former JoomGallery (e.g. JoomGallery 3.4.1) as well as a complete new installation works and give feedback. Thanks.
If successful I will merge the branch v3.5.0 to master, adjust the release date in the respective xml files and release the JoomGallery 3.5.0.
=> Preparations for the release of JoomGallery 3.5.0

.gitignore, administrator/components/com_joomgallery/helpers/upload.php, administrator/components/com_joomgallery/models/categories.php, administrator/components/com_joomgallery/models/image.php, administrator/components/com_joomgallery/models/images.php, components/com_joomgallery/models/edit.php, components/com_joomgallery/views/category/view.html.php, components/com_joomgallery/views/detail/view.html.php
Reverts JoomGalleryfriends/JoomGallery#58
=> Revert "Plugin events (new and modified)"

administrator/components/com_joomgallery/models/category.php, components/com_joomgallery/models/editcategory.php
This is a possible fix for issue https://github.com/JoomGalleryfriends/JoomGallery/issues/59
Thanks to wall007 for the suggestion.
=> [PHP8] fix error when creating main category

administrator/components/com_joomgallery/controllers/ajaxupload.php, administrator/components/com_joomgallery/controllers/batchupload.php, administrator/components/com_joomgallery/controllers/config.php, administrator/components/com_joomgallery/controllers/cssedit.php, administrator/components/com_joomgallery/controllers/ftpupload.php, administrator/components/com_joomgallery/controllers/jupload.php, administrator/components/com_joomgallery/controllers/maintenance.php, administrator/components/com_joomgallery/controllers/upload.php, administrator/language/en-GB/en-GB.com_joomgallery.ini
I tried to replace the still contained 'fixed text strings' in the component with language constants.
In doing so, I searched for typical text parts like 
no access...
you are not...
not allowed..
it is not...
but I am not sure if this is complete.
The occurrence in comments was not taken into consideration.
=> Add new language constants

administrator/components/com_joomgallery/script.php, script.php
Fix for the problem reported in https://github.com/JoomGalleryfriends/JoomGallery/issues/108
=> Fix warning during installation

administrator/components/com_joomgallery/changelog.xml, administrator/components/com_joomgallery/joomgallery.xml, administrator/components/com_joomgallery/script.php, joomgallery.xml
Final update for the release of JoomGallery 3.6.0
=> Prepare v3.6.0 release

administrator/components/com_joomgallery/changelog.xml, administrator/components/com_joomgallery/joomgallery.xml, administrator/components/com_joomgallery/script.php, joomgallery.xml, script.php
After a positive test of this [PR](https://github.com/JoomGalleryfriends/JoomGallery/pull/123) I would like to release the new version 3.6.1
=> Prepare for 3.6.1 Release

administrator/com_joomgallery/src/Model/CategoryModel.php, administrator/com_joomgallery/src/Service/FileManager/FileManager.php
=> Foldername when alias of migrated category changes

joomgallery.xml
This PR prepars the code für the bugfix-release 4.0.1
I think that all? @MrMusic
=> Prepare version 4.0.1

administrator/com_joomgallery/layouts/joomgallery/tip.php, administrator/com_joomgallery/src/Controller/JoomAdminController.php, administrator/com_joomgallery/src/Controller/JoomFormController.php, administrator/com_joomgallery/src/Model/JoomAdminModel.php, administrator/com_joomgallery/src/Service/Access/Base/AccessOwn.php, administrator/com_joomgallery/src/Service/Uploader/TUSUploader.php, administrator/com_joomgallery/src/View/Image/RawView.php
For many backend actions PHP notices are written to the server logfile. 
These can be deprecated notices or warnings.
The PHP notices do not cause a malfunction, but it is still better if the notices do not appear.
This PR fixes the following notices:
```
PHP Warning:  Attempt to read property "error" on null in administrator/components/com_joomgallery/src/Controller/JoomFormController.php on line 145
PHP Warning:  Undefined array key "id" in administrator/components/com_joomgallery/src/Controller/JoomFormController.php on line 235
PHP Warning:  Undefined variable $img_obj in administrator/components/com_joomgallery/src/View/Image/RawView.php on line 65
PHP Warning:  Attempt to read property "owner" on false in administrator/components/com_joomgallery/src/Service/Access/Base/AccessOwn.php …
```
=> Fix PHP notices with backend actions

administrator/com_joomgallery/sql/updates/mysql/4.1.0.sql, administrator/com_joomgallery/src/Service/Metadata/IptcDataEditor.php, administrator/com_joomgallery/src/Service/Metadata/Metadata.php, administrator/com_joomgallery/src/Service/Metadata/MetadataExifTool.php, administrator/com_joomgallery/src/Service/Metadata/MetadataPHP.php, administrator/com_joomgallery/src/Service/Metadata/PelDataEditor.php, joomgallery.xml, plugins/privacy/joomgallery/joomgallery.xml, plugins/system/joomgallery/joomgallery.xml, plugins/system/joomowner/joomowner.xml
This PR prepares the release of the next MINOR-Release of the JoomGallery.
Please test, if the component can be installed or updated properly and all the things work as expected.
1. open the pull request and scroll all the way down
2. open the ‘All checks have passed’ tab
3. click on the ‘PR Build Artifact’ link
4. switch to ‘Summary’ in the side menu on the left
5. download the existing ‘Artifact’ as a zip file
6. this zip can be installed as usual with the Joomla Installer
=> Release v4.1.0

crowdin.yml
This PR adds the language files of the plugins to the crowdin synchronisation.
=> Add plugin translations
