- administrator/components/com_joomgallery/helpers/upload.php
proper usage of the "Exif.Photo.UserComment" Meta-Tag.
This will fix the issue of the ASCIIA present when using Exif "UserComment".
> Fix use 'Exif.Photo.UserComment' for the ReplaceWithMetadata feature

- components/com_joomgallery/models/favourites.php
If the plugin 'System - K2' from K2 component (v2.10.3) is activated, the favorites function does not work. No zip file is created.
This change should resolve the conflict.
See also: https://www.forum.joomgalleryfriends.net/forum/index.php?thread/105-my-favourites-not-working/
> Favourites conflict with K2 system plugin

- administrator/components/com_joomgallery/models/maintenance.php
When using some batch jobs without selectet images a SQL error occurs
Go to Maintenance Manager - Tab Images
Select Batch Jobs: Delete images
Use Apply
Warning that no images have been selected
1064 You have an error in your SQL syntax...
The same is in the Categories tab
> Fix SQL error in some batch jobs in Maintenance Manager

- .gitignore
- administrator/components/com_joomgallery/helpers/upload.php
- administrator/components/com_joomgallery/models/categories.php
- administrator/components/com_joomgallery/models/image.php
- administrator/components/com_joomgallery/models/images.php
- components/com_joomgallery/models/edit.php
- components/com_joomgallery/views/category/view.html.php
- components/com_joomgallery/views/detail/view.html.php
During my work with the JoomGallery I missed some Plugin events.
Especially for actions performed in the images list view (change state, recreate, rotate) I would like to have additional event triggers. During the upload process I miss some information in the onJoomBeforeUpload, in order to know which image will be uploaded after the event.
> Plugin events (new and modified)

- administrator/language/en-GB/en-GB.com_joomgallery.sys.ini
This PR adds some language constants in en-GB.com_joomgallery.sys.ini.
The language constants are required in the Joomla users 'Advanced Permissions Report'.
> Add missing language constants

- administrator/components/com_joomgallery/helpers/html/joomgallery.php
- components/com_joomgallery/views/category/view.html.php
Adds the anchor in the link to the detail view in the category view.
I'm not sure if this pull request should be directed to the master or 3.6.0 branch?
Since there is a configuration setting for it, it could be seen as a bug because the setting was ignored.
> Add anchor to image link in the category view

- administrator/components/com_joomgallery/models/categories.php
- administrator/language/en-GB/en-GB.com_joomgallery.ini
The deletion of non-empty categories in the backend is not possible anymore since Joomla applies a Html input filter on alert messages introduced as security fix in Joomla 3.9.25.
This pull request should fix that.
Additionally I have removed the checkbox in front of the "Delete completely" button, because firstly I think it is not neccessary to have another security question inside the message that is a security question itself and secondly the neccessary script would be filtered by Joomla either.
> Fix deletion of non-empty categories in the backend

- administrator/components/com_joomgallery/access.xml
- administrator/components/com_joomgallery/controllers/images.php
- administrator/components/com_joomgallery/helpers/helper.php
- administrator/components/com_joomgallery/models/categories.php
- administrator/components/com_joomgallery/models/images.php
- administrator/components/com_joomgallery/views/categories/view.html.php
- administrator/components/com_joomgallery/views/images/view.html.php
- administrator/language/en-GB/en-GB.com_joomgallery.ini
- administrator/language/en-GB/en-GB.com_joomgallery.sys.ini
- components/com_joomgallery/models/edit.php
- components/com_joomgallery/models/editcategory.php
- components/com_joomgallery/views/category/view.html.php
- components/com_joomgallery/views/detail/view.html.php
- components/com_joomgallery/views/favourites/view.html.php
- components/com_joomgallery/views/search/view.html.php
- components/com_joomgallery/views/toplist/view.html.php
- components/com_joomgallery/views/usercategories/tmpl/default.php
- components/com_joomgallery/views/userpanel/view.html.php
At the moment there is only one setting 'delete' in the Joomla ACL. There is no option to limit deletion to 'own' content.
This PR extends the permission in the JoomGallery by the action 'delete own' (joom.delete.own).
This allows users to be given the permission to delete their 'own' categories or images without at the same time being granted the authorization to delete categories or images of other users.
I am very appreciative for suggestions for improvement.
> Add 'delete own' permission

- administrator/components/com_joomgallery/views/images/view.html.php
- administrator/language/en-GB/en-GB.com_joomgallery.ini
At the moment, the selected images are deleted immediately when you click on Delete in Image Manager.
This can lead to loss of data if delete is accidentally clicked instead of another button.
This PR adds an additional security question.
> Add a security question in image manager

- components/com_joomgallery/views/category/view.feed.php
JoomGallery does not respect the setting 'no e-mail' in global configuration of Joomla.
See https://www.forum.joomgalleryfriends.net/forum/index.php?thread/285-remove-user-emails-from-rss-feed/
This PR should fix this.
> Fix Email in Category Feed

- administrator/components/com_joomgallery/helpers/config.php
- administrator/components/com_joomgallery/helpers/html/joomselect.php
- administrator/components/com_joomgallery/sql/install.mysql.utf8.sql
- administrator/components/com_joomgallery/sql/setdefault.install.mysql.utf8.sql
- administrator/components/com_joomgallery/sql/updates/mysql/3.6.0.sql
- administrator/components/com_joomgallery/views/config/tmpl/default.php
- administrator/language/en-GB/en-GB.com_joomgallery.ini
- components/com_joomgallery/models/search.php
This PR integrates external search engines into JoomGallery. External search engines needs to have a Plugin of group="joomgallery" and the plugin events "onJoomSearchEngineGetName" and "onJoomSearch".
A configuration option is added to the configuration manager. The option is found in the search tab. Any external search engine which has a JoomGallery-Plugin installed and enabled will be listed there in the config manager. There you can select which search engine you want to use to create the search view.
The serach form field in the header of JoomGallery will generate the search view based on the selected search engine.
- PR #78 (More plugin events)
- A suitable search plugin (e.g https://github.com/JoomGalleryfriends/JoomFinderPlugin)
Since this PR depends on the PR #78 I will do a …
> External search engines integration

- administrator/components/com_joomgallery/models/image.php
- components/com_joomgallery/models/edit.php
When moving an image, there was a PHP error when modifications could not be written to the database for example if there is an error happening within a Plugin.
`0  Too few arguments to function JError::raiseWarning(), 1 passed in /data/www/www152/www/administrator/components/com_joomgallery/models/image.php on line 1190 and at least 2 expected`
The method [JError::raiseWarning](https://api.joomla.org/cms-3/classes/JError.html#method_raiseWarning) expects the first argument to be an application internal error code. Since JoomGallery does not use this internal error codes, a random error code was inserted in order to get rid of the PHP error and to get the correct error message from the Table object.
> Add error code to JError::raiseWarning method

- administrator/components/com_joomgallery/controllers/categories.json.php
- administrator/components/com_joomgallery/controllers/categories.php
- administrator/components/com_joomgallery/controllers/comments.php
- administrator/components/com_joomgallery/controllers/config.php
- administrator/components/com_joomgallery/controllers/images.json.php
- administrator/components/com_joomgallery/controllers/images.php
- administrator/components/com_joomgallery/controllers/maintenance.php
- administrator/components/com_joomgallery/models/comments.php
- administrator/components/com_joomgallery/models/editimages.php
- administrator/components/com_joomgallery/models/fields/thumbnail.php
- administrator/components/com_joomgallery/models/image.php
- administrator/components/com_joomgallery/models/maintenance.php
- administrator/components/com_joomgallery/models/move.php
- administrator/components/com_joomgallery/views/editimages/view.html.php
- components/com_joomgallery/controllers/categories.json.php
- components/com_joomgallery/controllers/image.php
- components/com_joomgallery/controllers/images.json.php
- components/com_joomgallery/models/editcategory.php
- components/com_joomgallery/views/edit/view.html.php
Fixes a security issue in JoomGallery v3.x. 
**Problem:**
`JRequest::getVar('cid', array(), '', 'array');`
This method does not sanitize the input variable properly. At some locations in the code, the retreived input variable was passed directly to the DB which allows attacks of type SQL Injection.
> Fix vulnerability type SQL Injection

- administrator/components/com_joomgallery/view.php
- administrator/language/en-GB/en-GB.com_joomgallery.ini
- components/com_joomgallery/view.php
- language/en-GB/en-GB.com_joomgallery.ini
Adds a warning message to all JoomGallery views if the version in the XML component manifest file contains `-dev`, `-alpha`, `-beta` or`-rc`.
This should warn users to use such versions on productive sites.
> Add development warning message

- administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
- administrator/com_joomgallery/src/Model/CategoryModel.php
- administrator/com_joomgallery/src/Model/MigrationModel.php
- administrator/com_joomgallery/src/Table/CategoryTable.php
- administrator/com_joomgallery/src/Table/MigrationTableTrait.php
This PR fixes the following issue:
- Activated compatibility mode
- Migration of an existing Joomla installation (variant 1) with `Use new folder structure = No` and `image usage= Direct usage`
**This results in** 
->the folders remain as they are (i.e. with the id at the end)
->in the DB the field `static_path` is empty
> Fix issue during migration: static-path missing

- plugins/system/joomgallery/src/Extension/Joomgallery.php
This PR fixes the issue #147 
JoomGallery fields are shown in user forms in the backend but not in the frontend
> Remove JG fields from frontend forms

- media/com_joomgallery/css/site.css
Possible fix for https://github.com/JoomGalleryfriends/JoomGallery/issues/161
This should make the links to subcategories visible even with 'dark' templates.
> Remove jg-link color from site.css

- administrator/com_joomgallery/forms/category.xml
- administrator/com_joomgallery/forms/collection.xml
- administrator/com_joomgallery/forms/image.xml
- site/com_joomgallery/forms/categoryform.xml
- site/com_joomgallery/forms/imageform.xml
In Joomla! 5 the length of the meta description field has been changed from 160 to 300 characters. See https://github.com/joomla/joomla-cms/pull/41795
This PR adjusts the JoomGallery meta description field so that they match those of Joomla.
```
label="JFIELD_META_DESCRIPTION_LABEL"
rows="3"
cols="30"
maxlength="300"
```
Enter a meta description for categories and images. This may be a maximum of 300 characters long.
> Adjustment of the Meta Description

- administrator/com_joomgallery/src/View/Control/HtmlView.php
- administrator/com_joomgallery/tmpl/control/default.php
Fix for issue https://github.com/JoomGalleryfriends/JoomGallery/issues/196
In addition, a missing equals sign is added in the tmpl file.
The buttons in the toolbar have no space to each other 
The buttons have the normal spacing
> Fix button layout in control panel

- administrator/components/com_joomgallery/sql/install.mysql.utf8.sql
- administrator/components/com_joomgallery/sql/updates/mysql/3.7.1.sql
If the length of the **entire system path** of a **category** or an **image** exceeds 255 characters, an error occurs in the maintenance manager.
See https://www.forum.joomgalleryfriends.net/forum/index.php?thread/477-vorbereitung-migration-3-7cr1-waisen-die-keine-waisen-sind/
This is due to the restriction of the **fullpath** column in database table **#__joomgallery_orphans** to 255 characters.
This PR extends the column to 500 characters so that no errors occur in the maintenance manager.
> Increase length of DB column fullpath

- media/com_joomgallery/js/joomgrid.js
- site/com_joomgallery/tmpl/category/default_cat.php
- site/com_joomgallery/tmpl/gallery/default.php
This PR adds the possibility to add multiple grid views and lightGallery slideshows on one page.
This comes very handy when having a content plugin and/or image modules appearing at the same page.
- Component views, gallery view and category view, should still work as before.
- With a component Plugin (e.g JoomPlu), add multiple images or category walls in one article.
--> They should properly show up and having individual lightGalleries (slideshows).
> Multiple image grids and lightGalleries

- administrator/com_joomgallery/src/Model/MigrationModel.php
This PR fixes the issue #204.
The filesystem is now taken from the config service before safing to the database during migration.
> [Fix] Filesystem during migration

- docs/Upmerge.md
- docs/Upmerge_en.md
This PR adds documentation on how to perform an upmerge from the master branch to a MINOR-Release Branch (e.g v4.1.0).
> Add upmerge docs

- media/com_joomgallery/js/joomgrid.js
- site/com_joomgallery/tmpl/category/default_cat.php
This pull request allows you to set the number of images displayed and the number of images to be reloaded in the settings. The two fields # Images and # Images Reloaded were previously ignored. In addition, the load more button is only displayed if the total number of images exceeds the value of # images.
> [Feature] load more pagination takes over settings

- administrator/com_joomgallery/src/View/Image/RawView.php
- site/com_joomgallery/src/View/Image/RawView.php
This PR fixes issue reported in https://github.com/JoomGalleryfriends/JoomGallery/issues/223.
Before applying this PR, thumbnails of unpublished images are not shown in the images list view in the frontend.
1. Upload an image from with user which is not super user
2. Unpublish the uploaded image after upload
3. Login to the frontend with the user uploaded the image
4. Visit the image list view in the fronted
5. Thumbnail of your unpublished image should be visible.
> [Feature] Provide access to thumbnails for creator

- script.php
One of the PRs added to JoomGallery v4.1.0 which added a working changelog button, created an issue in Joomla! versions older than v5.1.0.
PR which added the changelog button:
[#235](https://github.com/JoomGalleryfriends/JoomGallery/pull/235)
PR which changed the way how to create bootstrap modal boxes in Joomla!:
https://github.com/joomla/joomla-cms/pull/42447
So the code introduced in #235 creates an error in the update script when perfomed in Joomla! versions before v5.1.0
This PR fixes this issue.
Install JoomGallery v4.0.1 on a Joomla! version v5.0.3 or older.
Than install this PR. The component should be updated successfully.
> Fix update issue in Joomla! < v5.1

- .github/workflows/pr-build.yml
- .github/workflows/release.yml
This PR improved the script which is run by GitHub on a PR or on a release to create an installable zip file containing all 3rd party libraries.
The improvement mainly exists on cleaning up the installed repository folder of the pel library by deleteing everything which is not really needed for running the code.
The zip file created has a size of about 4,6 MB
The zip file created has a size of about 1,5 MB
The zip created by the script (artifact) should be installable and everything should still work.
> Improve zip creation script

- media/com_joomgallery/js/joomgrid.js
This PR fixes the issue that multiple justified grids are displayed correctly.
Before this PR, only one justified grid was diapleyed correctly. Every other justified grids have their images one below the other. one line per image.
Install the PR and a content plugin allowing multiple image grids display. Add at least two category grids into one article and choose the layout `justified`. With this PR applied, all category grids should be displayed correctly.
> [Fix] Allow multiple justified grids

- administrator/com_joomgallery/src/Extension/JoomgalleryComponent.php
- administrator/com_joomgallery/src/Helper/JoomHelper.php
- administrator/com_joomgallery/src/Service/Config/ConfigInterface.php
- administrator/com_joomgallery/src/Service/Config/ConfigServiceInterface.php
- administrator/com_joomgallery/src/Service/Config/ConfigServiceTrait.php
- administrator/com_joomgallery/src/Service/Filesystem/FilesystemServiceInterface.php
- administrator/com_joomgallery/src/Service/Filesystem/FilesystemServiceTrait.php
- administrator/com_joomgallery/src/Service/Messenger/PmMessenger.php
- administrator/com_joomgallery/src/Service/Refresher/RefresherInterface.php
- administrator/com_joomgallery/src/Service/Refresher/RefresherServiceInterface.php
- administrator/com_joomgallery/src/Service/Refresher/RefresherServiceTrait.php
- administrator/com_joomgallery/src/Service/Uploader/HTMLUploader.php
- administrator/com_joomgallery/src/Service/Uploader/SingleUploader.php
- administrator/com_joomgallery/src/Service/Uploader/TUSUploader.php
- administrator/com_joomgallery/src/Service/Uploader/Uploader.php
- administrator/com_joomgallery/src/Service/Uploader/UploaderInterface.php
- administrator/com_joomgallery/src/Service/Uploader/UploaderServiceInterface.php
- administrator/com_joomgallery/src/Service/Uploader/UploaderServiceTrait.php
- script.php
This PR fixes the issue reported in #250 
There were still some J6 deprecations in the code which made JoomGallery break in Joomla 6. This PR should remove this deprecations.
Install the PR on a fresh Joomla 6 installations. Everything should work as you know it from within Joomla 5. No PHP errors.
> [Fix] Remove forgotten J6 deprecations
